name: Upload blob report
description: Uploads blob report from shards

inputs:
  shardIndex:
    required: true

runs:
  using: composite
  steps:
    - name: Upload blob report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: blob-report-${{ inputs.shardIndex }}
        path: blob-report
        retention-days: 1
