name: Upload HTML report
description: Uploads HTML report

runs:
  using: composite
  steps:
    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: html-report--attempt-${{ github.run_attempt }}
        path: playwright-report
        retention-days: 14
