name: Run application
description: Runs application for tests.

runs:
    using: composite
    steps:
        - name: Checkout app
          uses: actions/checkout@v4
          with:
            repository: jaktestowac/rolnopol
        - name: Run app
          shell: bash
          run: |
            npm i
            npm run start &
        - name: Wait for app
          shell: bash
          run: npx wait-on http://localhost:3000