name: Run application
description: Runs application for tests.

runs:
    using: composite
    steps:
        - name: Checkout app
          uses: actions/checkout@v4
          with:
            repository: jaktestowac/rolnopol
            path: app
        - name: Run app
          shell: bash
          run: |
            cd app
            npm i
            nohup npm run start &