name: Merge HTML reports
on: 
  workflow_call:

jobs:
  merge-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository for tests
        uses: actions/checkout@v4
   
      - name: Setup Node.js
        uses: ./.github/actions/setup_node

      - name: Install dependencies
        uses: ./.github/actions/install_dependencies

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v5
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true

      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html ./all-blob-reports

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report--attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 14