name: Merge Request
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  playwright:
    name: Merge request for Playwright
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        shell: bash
        run: npm ci

      - name: Run typecheck
        shell: bash
        run: npx tsc --noEmit

      - name: Run ESLint
        shell: bash
        run: npx eslint

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
