name: Run tests
on: 
  workflow_dispatch:
    inputs:
      browser:
        description: Select browser to run tests
        required: true
        default: all
        type: choice
        options:
          - all
          - chromium
          - firefox
          - safari
      workers:
        description: Select of workers. Can be either number ("1") or percentage of available CPU ("50%").
        required: true
        default: "100%"
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  tests:
    name: Run tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.60.0-noble
      options: --user root
    env:
      HOME: /root
    steps:
      - name: Checkout repository for .github changes
        uses: actions/checkout@v4

      - name: Download and run application
        uses: ./.github/actions/run_app

      - name: Checkout repository for tests
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Setup Node.js
        uses: ./.github/actions/setup_node

      - name: Install dependencies
        uses: ./.github/actions/install_dependencies

      - name: Run Playwright tests
        uses: ./.github/actions/run_playwright_tests
        with: 
          browser: ${{ inputs.browser }}
          workers: ${{ inputs.workers }}

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 10
